services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /mnt/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always
