services:
  grafana:
    image: grafana/grafana:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.vast-data.vast-survey.org`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=lets-encrypt
    networks:
      - monitoring
      - public
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus:latest
    networks:
      - monitoring
      - public
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - monitoring
      - public
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /mnt/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always

networks:
  monitoring:
  public:
    # external: true
