{
 "title": "Docker - Interactive",
 "description": "Docker metrics for the vast-interactive server.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Container status, by group.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/4" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\"vast-jupyterhub-hub-1|vast-jupyterhub-database-1|interactive-cadvisor-1|traefik\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\"jupyter.*\"})",
     "legendFormat": "Instances"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\"vast-jupyterhub.*\"})",
     "legendFormat": "JupyterHub"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\".*(cadvisor).*\"})",
     "legendFormat": "Monitoring"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\"traefik\"})",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Current 1m CPU usage rate.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name!~\"\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_load1{instance=\"131.217.179.90:9100\"}) / count(rate(node_cpu_seconds_total{instance=\"131.217.179.90:9100\", mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "count(rate(node_cpu_seconds_total{instance=\"131.217.179.90:9100\", mode=\"system\"}[1m]))",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name!~\"\"}) ",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.179.90:9100\"} - node_memory_MemAvailable_bytes{instance=\"131.217.179.90:9100\"}",
     "legendFormat": "System"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.179.90:9100\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Current in-use storage.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name!~\"\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.90:9100\", mountpoint=\"/mnt/docker\"} - node_filesystem_avail_bytes{instance=\"131.217.179.90:9100\", mountpoint=\"/mnt/docker\"}",
     "legendFormat": "System"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.90:9100\" ,mountpoint=\"/mnt/docker\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Names of running containers.",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name!~\"\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "description": "History of 1m CPU usage rate.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name!~\"\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name!~\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Storage History",
   "type": "timeseries",
   "description": "History of in-use storage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name!~\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Jupyter Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Status History",
   "type": "state-timeline",
   "description": "History of container status.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\"jupyter-.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Current 1m CPU usage rate.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name=~\"jupyter-.*\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name=~\"jupyter-.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Current in-use storage.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name=~\"jupyter-.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "Current download network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.90:8080\", name=~\"jupyter-.*\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "Current upload network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.90:8080\", name=~\"jupyter-.*\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "description": "History of 1m CPU usage rate.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name=~\"jupyter-.*\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name=~\"jupyter-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage History",
   "type": "timeseries",
   "description": "History of in-use storage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name=~\"jupyter-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "JupyterHub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Container status.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-hub-1\"}) or on() vector(0)",
     "legendFormat": "Hub"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-database-1\"}) or on() vector(0)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Current 1m CPU usage rate.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-hub-1\"}[1m])) by (name)",
     "legendFormat": "Hub"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-database-1\"}[1m])) by (name)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-hub-1\"}) by (name)",
     "legendFormat": "Hub"
    },
    {
     "expr": "avg(container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-database-1\"}) by (name)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Current in-use storage.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-hub-1\"}) by (name)",
     "legendFormat": "Hub"
    },
    {
     "expr": "avg(container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-database-1\"}) by (name)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "Current download network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-hub-1\"}[1m]))",
     "legendFormat": "Hub"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-database-1\"}[1m]))",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "Current upload network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-hub-1\"}[1m]))",
     "legendFormat": "Hub"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-database-1\"}[1m]))",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Status History",
   "type": "state-timeline",
   "description": "History of container status.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-hub-1\"}) OR on() vector(0)",
     "legendFormat": "Hub"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-database-1\"}) OR on() vector(0)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "description": "History of 1m CPU usage rate.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-hub-1\"}[1m])",
     "legendFormat": "Hub"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-database-1\"}[1m])",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-hub-1\"}",
     "legendFormat": "Hub"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-database-1\"}",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Storage History",
   "type": "timeseries",
   "description": "History of in-use storage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-hub-1\"}",
     "legendFormat": "Hub"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-database-1\"}",
     "legendFormat": "Database"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Container status.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"interactive-cadvisor-1\"}) or on() vector(0)",
     "legendFormat": "Monitoring"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"traefik\"}) or on() vector(0)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Current 1m CPU usage rate.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name=\"interactive-cadvisor-1\"}[1m])) by (name)",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name=\"traefik\"}[1m])) by (name)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name=\"interactive-cadvisor-1\"}) by (name)",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "avg(container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name=\"traefik\"}) by (name)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Current in-use storage.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name=\"interactive-cadvisor-1\"}) by (name)",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "avg(container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name=\"traefik\"}) by (name)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "Current download network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.90:8080\", name=\"interactive-cadvisor-1\"}[1m]))",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.90:8080\", name=\"traefik\"}[1m]))",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "Current upload network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.90:8080\", name=\"interactive-cadvisor-1\"}[1m]))",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.90:8080\", name=\"traefik\"}[1m]))",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Status History",
   "type": "state-timeline",
   "description": "History of container status.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"interactive-cadvisor-1\"}) OR on() vector(0)",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"traefik\"}) OR on() vector(0)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "description": "History of 1m CPU usage rate.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name=\"interactive-cadvisor-1\"}[1m])",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.90:8080\", name=\"traefik\"}[1m])",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name=\"interactive-cadvisor-1\"}",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.90:8080\", name=\"traefik\"}",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Storage History",
   "type": "timeseries",
   "description": "History of in-use storage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name=\"interactive-cadvisor-1\"}",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.90:8080\", name=\"traefik\"}",
     "legendFormat": "Traefik"
    }
   ]
  }
 ]
}