{
 "title": "Docker - Admin",
 "description": "Docker metrics for the vast-admin server.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Container status.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"admin-grafana-1\"}) or on() vector(0)",
     "legendFormat": "Grafana"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"admin-prometheus-1\"}) or on() vector(0)",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"admin-cadvisor-1\"}) or on() vector(0)",
     "legendFormat": "CAdvisor"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Current 1m CPU usage rate.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.250:8080\", name=\"admin-grafana-1\"}[1m])",
     "legendFormat": "Grafana"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.250:8080\", name=\"admin-prometheus-1\"}[1m])",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.250:8080\", name=\"admin-cadvisor-1\"}[1m])",
     "legendFormat": "CAdvisor"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-grafana-1\"}",
     "legendFormat": "Grafana"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-prometheus-1\"}",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-cadvisor-1\"}",
     "legendFormat": "CAdvisor"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Current in-use storage.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-grafana-1\"}",
     "legendFormat": "Grafana"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-prometheus-1\"}",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-cadvisor-1\"}",
     "legendFormat": "CAdvisor"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "Current download network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.250:8080\", name=\"admin-grafana-1\"}[1m]))",
     "legendFormat": "Grafana"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.250:8080\", name=\"admin-prometheus-1\"}[1m]))",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.250:8080\", name=\"admin-cadvisor-1\"}[1m]))",
     "legendFormat": "CAdvisor"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "Current upload network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.250:8080\", name=\"admin-grafana-1\"}[1m]))",
     "legendFormat": "Grafana"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.250:8080\", name=\"admin-prometheus-1\"}[1m]))",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.250:8080\", name=\"admin-cadvisor-1\"}[1m]))",
     "legendFormat": "CAdvisor"
    }
   ]
  },
  {
   "title": "Status History",
   "type": "state-timeline",
   "description": "History of container status.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"admin-grafana-1\"}) OR on() vector(0)",
     "legendFormat": "Grafana"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"admin-prometheus-1\"}) OR on() vector(0)",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"admin-cadvisor-1\"}) OR on() vector(0)",
     "legendFormat": "CAdvisor"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "description": "History of 1m CPU usage rate.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.250:8080\", name=\"admin-grafana-1\"}[1m])",
     "legendFormat": "Grafana"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.250:8080\", name=\"admin-prometheus-1\"}[1m])",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.250:8080\", name=\"admin-cadvisor-1\"}[1m])",
     "legendFormat": "CAdvisor"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-grafana-1\"}",
     "legendFormat": "Grafana"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-prometheus-1\"}",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-cadvisor-1\"}",
     "legendFormat": "CAdvisor"
    }
   ]
  },
  {
   "title": "Storage History",
   "type": "timeseries",
   "description": "History of in-use storage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-grafana-1\"}",
     "legendFormat": "Grafana"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-prometheus-1\"}",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.250:8080\", name=\"admin-cadvisor-1\"}",
     "legendFormat": "CAdvisor"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Container status.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"traefik\"}) or on() vector(0)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Current 1m CPU usage rate.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.250:8080\", name=\"traefik\"}[1m])",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.250:8080\", name=\"traefik\"}",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Current in-use storage.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.250:8080\", name=\"traefik\"}",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "Current download network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.250:8080\", name=\"traefik\"}[1m]))",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "Current upload network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.250:8080\", name=\"traefik\"}[1m]))",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Status History",
   "type": "state-timeline",
   "description": "History of container status.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"traefik\"}) OR on() vector(0)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "description": "History of 1m CPU usage rate.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.250:8080\", name=\"traefik\"}[1m])",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.250:8080\", name=\"traefik\"}",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Storage History",
   "type": "timeseries",
   "description": "History of in-use storage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.250:8080\", name=\"traefik\"}",
     "legendFormat": "Trraefik"
    }
   ]
  }
 ]
}