{
 "title": "Docker - WebApp",
 "description": "Docker metrics for the vast-webapp server.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Container status, by group.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/13" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\"vast-pipeline-pipeline-1|vast-pipeline-database-1|vast-pipeline-index-web-1|vast-pipeline-index-database-1|validation-app-1|validation-database-1|carta-devops-backend-1|carta-devops-database-1|radio-star-catalogue-web-1|radio-star-catalogue-db-1|pghero-app-1|webapp-cadvisor-1|traefik\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\"vast-pipeline.*\"})",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\"(validation|carta).*\"})",
     "legendFormat": "Validation"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\"radio-star-catalogue.*\"})",
     "legendFormat": "Catalogue"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\".*(pghero|cadvisor).*\"})",
     "legendFormat": "Monitoring"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\"traefik\"})",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Current 1m CPU usage rate.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name!~\"\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_load1{instance=\"131.217.179.25:9100\"}) / count(rate(node_cpu_seconds_total{instance=\"131.217.179.25:9100\", mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "count(rate(node_cpu_seconds_total{instance=\"131.217.179.25:9100\", mode=\"system\"}[1m]))",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name!~\"\"}) ",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.179.25:9100\"} - node_memory_MemAvailable_bytes{instance=\"131.217.179.25:9100\"}",
     "legendFormat": "System"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.179.25:9100\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Current in-use storage.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name!~\"\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/mnt/docker\"} - node_filesystem_avail_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/mnt/docker\"}",
     "legendFormat": "System"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.25:9100\" ,mountpoint=\"/mnt/docker\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Names of running containers.",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name!~\"\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "description": "History of 1m CPU usage rate.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name!~\"\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name!~\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Storage History",
   "type": "timeseries",
   "description": "History of in-use storage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name!~\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Container status.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-pipeline-1\"}) or on() vector(0)",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-database-1\"}) or on() vector(0)",
     "legendFormat": "Database"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-web-1\"}) or on() vector(0)",
     "legendFormat": "Index"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-database-1\"}) or on() vector(0)",
     "legendFormat": "Index DB"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Current 1m CPU usage rate.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-pipeline-1\"}[1m])) by (name)",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-database-1\"}[1m])) by (name)",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-web-1\"}[1m])) by (name)",
     "legendFormat": "Index"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-database-1\"}[1m])) by (name)",
     "legendFormat": "Index DB"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-pipeline-1\"}) by (name)",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-database-1\"}) by (name)",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-web-1\"}) by (name)",
     "legendFormat": "Index"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-database-1\"}) by (name)",
     "legendFormat": "Index DB"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Current in-use storage.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-pipeline-1\"}) by (name)",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-database-1\"}) by (name)",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-web-1\"}) by (name)",
     "legendFormat": "Index"
    },
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-database-1\"}) by (name)",
     "legendFormat": "Index DB"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "Current download network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-pipeline-1\"}[1m]))",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-database-1\"}[1m]))",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-web-1\"}[1m]))",
     "legendFormat": "Index"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-database-1\"}[1m]))",
     "legendFormat": "Index DB"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "Current upload network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-pipeline-1\"}[1m]))",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-database-1\"}[1m]))",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-web-1\"}[1m]))",
     "legendFormat": "Index"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-database-1\"}[1m]))",
     "legendFormat": "Index DB"
    }
   ]
  },
  {
   "title": "Status History",
   "type": "state-timeline",
   "description": "History of container status.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-pipeline-1\"}) OR on() vector(0)",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-database-1\"}) OR on() vector(0)",
     "legendFormat": "Database"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-web-1\"}) OR on() vector(0)",
     "legendFormat": "Index"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-database-1\"}) OR on() vector(0)",
     "legendFormat": "Index DB"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "description": "History of 1m CPU usage rate.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-pipeline-1\"}[1m])",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-database-1\"}[1m])",
     "legendFormat": "Database"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-web-1\"}[1m])",
     "legendFormat": "Index"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-database-1\"}[1m])",
     "legendFormat": "Index DB"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-pipeline-1\"}",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-database-1\"}",
     "legendFormat": "Database"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-web-1\"}",
     "legendFormat": "Index"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-database-1\"}",
     "legendFormat": "Index DB"
    }
   ]
  },
  {
   "title": "Storage History",
   "type": "timeseries",
   "description": "History of in-use storage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-pipeline-1\"}",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-database-1\"}",
     "legendFormat": "Database"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-web-1\"}",
     "legendFormat": "Index"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-database-1\"}",
     "legendFormat": "Index DB"
    }
   ]
  },
  { "title": "Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Container status.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"validation-app-1\"}) or on() vector(0)",
     "legendFormat": "App"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"validation-database-1\"}) or on() vector(0)",
     "legendFormat": "Database"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"carta-devops-backend-1\"}) or on() vector(0)",
     "legendFormat": "Carta"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}) or on() vector(0)",
     "legendFormat": "Carta DB"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Current 1m CPU usage rate.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"validation-app-1\"}[1m])) by (name)",
     "legendFormat": "App"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"validation-database-1\"}[1m])) by (name)",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}[1m])) by (name)",
     "legendFormat": "Carta"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}[1m])) by (name)",
     "legendFormat": "Carta DB"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"validation-app-1\"}) by (name)",
     "legendFormat": "App"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"validation-database-1\"}) by (name)",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"carta-devops-backend-1\"}) by (name)",
     "legendFormat": "Carta"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}) by (name)",
     "legendFormat": "Carta DB"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Current in-use storage.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"validation-app-1\"}) by (name)",
     "legendFormat": "App"
    },
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"validation-database-1\"}) by (name)",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}) by (name)",
     "legendFormat": "Carta"
    },
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}) by (name)",
     "legendFormat": "Carta DB"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "Current download network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"validation-app-1\"}[1m]))",
     "legendFormat": "App"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"validation-database-1\"}[1m]))",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"carta-devops-backend-1\"}[1m]))",
     "legendFormat": "Carta"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}[1m]))",
     "legendFormat": "Carta DB"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "Current upload network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"validation-app-1\"}[1m]))",
     "legendFormat": "App"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"validation-database-1\"}[1m]))",
     "legendFormat": "Database"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"carta-devops-backend-1\"}[1m]))",
     "legendFormat": "Carta"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}[1m]))",
     "legendFormat": "Carta DB"
    }
   ]
  },
  {
   "title": "Status History",
   "type": "state-timeline",
   "description": "History of container status.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"validation-app-1\"}) OR on() vector(0)",
     "legendFormat": "App"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"validation-database-1\"}) OR on() vector(0)",
     "legendFormat": "Database"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"carta-devops-backend-1\"}) OR on() vector(0)",
     "legendFormat": "Carta"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}) OR on() vector(0)",
     "legendFormat": "Carta DB"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "description": "History of 1m CPU usage rate.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"validation-app-1\"}[1m])",
     "legendFormat": "App"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"validation-database-1\"}[1m])",
     "legendFormat": "Database"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"carta-devops-backend-1\"}[1m])",
     "legendFormat": "Carta"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}[1m])",
     "legendFormat": "Carta DB"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"validation-app-1\"}",
     "legendFormat": "App"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"validation-database-1\"}",
     "legendFormat": "Database"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"carta-devops-backend-1\"}",
     "legendFormat": "Carta"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}",
     "legendFormat": "Carta DB"
    }
   ]
  },
  {
   "title": "Storage History",
   "type": "timeseries",
   "description": "History of in-use storage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"validation-app-1\"}",
     "legendFormat": "App"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"validation-database-1\"}",
     "legendFormat": "Database"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"carta-devops-backend-1\"}",
     "legendFormat": "Carta"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}",
     "legendFormat": "Carta DB"
    }
   ]
  },
  { "title": "Radio Star Catalogue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Container status.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-web-1\"}) or on() vector(0)",
     "legendFormat": "Web"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-db-1\"}) or on() vector(0)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Current 1m CPU usage rate.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-web-1\"}[1m])) by (name)",
     "legendFormat": "Web"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-db-1\"}[1m])) by (name)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-web-1\"}) by (name)",
     "legendFormat": "Web"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-db-1\"}) by (name)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Current in-use storage.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-web-1\"}) by (name)",
     "legendFormat": "Web"
    },
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-db-1\"}) by (name)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "Current download network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-web-1\"}[1m]))",
     "legendFormat": "Web"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-db-1\"}[1m]))",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "Current upload network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-web-1\"}[1m]))",
     "legendFormat": "Web"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-db-1\"}[1m]))",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Status History",
   "type": "state-timeline",
   "description": "History of container status.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-web-1\"}) OR on() vector(0)",
     "legendFormat": "Web"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-db-1\"}) OR on() vector(0)",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "description": "History of 1m CPU usage rate.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-web-1\"}[1m])",
     "legendFormat": "Web"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-db-1\"}[1m])",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-web-1\"}",
     "legendFormat": "Web"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-db-1\"}",
     "legendFormat": "Database"
    }
   ]
  },
  {
   "title": "Storage History",
   "type": "timeseries",
   "description": "History of in-use storage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-web-1\"}",
     "legendFormat": "Web"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-db-1\"}",
     "legendFormat": "Database"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Container status.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"pghero-app-1\"}) or on() vector(0)",
     "legendFormat": "PGHero"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"webapp-cadvisor-1\"}) or on() vector(0)",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"traefik\"}) or on() vector(0)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Current 1m CPU usage rate.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"pghero-app-1\"}[1m])) by (name)",
     "legendFormat": "PGHero"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"webapp-cadvisor-1\"}[1m])) by (name)",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"traefik\"}[1m])) by (name)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"pghero-app-1\"}) by (name)",
     "legendFormat": "PGHero"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"webapp-cadvisor-1\"}) by (name)",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"traefik\"}) by (name)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "description": "Current in-use storage.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"pghero-app-1\"}) by (name)",
     "legendFormat": "PGHero"
    },
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"webapp-cadvisor-1\"}) by (name)",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "sum(container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"traefik\"}) by (name)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "Current download network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"pghero-app-1\"}[1m]))",
     "legendFormat": "PGHero"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"webapp-cadvisor-1\"}[1m]))",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=\"131.217.179.25:8080\", name=\"traefik\"}[1m]))",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "description": "Current upload network rates, per container.",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"pghero-app-1\"}[1m]))",
     "legendFormat": "PGHero"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"webapp-cadvisor-1\"}[1m]))",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=\"131.217.179.25:8080\", name=\"traefik\"}[1m]))",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Status History",
   "type": "state-timeline",
   "description": "History of container status.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"pghero-app-1\"}) OR on() vector(0)",
     "legendFormat": "PGHero"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"webapp-cadvisor-1\"}) OR on() vector(0)",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"traefik\"}) OR on() vector(0)",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "CPU History",
   "type": "timeseries",
   "description": "History of 1m CPU usage rate.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"pghero-app-1\"}[1m])",
     "legendFormat": "PGHero"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"webapp-cadvisor-1\"}[1m])",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"131.217.179.25:8080\", name=\"traefik\"}[1m])",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"pghero-app-1\"}",
     "legendFormat": "PGHero"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"webapp-cadvisor-1\"}",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"131.217.179.25:8080\", name=\"traefik\"}",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Storage History",
   "type": "timeseries",
   "description": "History of in-use storage.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"pghero-app-1\"}",
     "legendFormat": "PGHero"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"webapp-cadvisor-1\"}",
     "legendFormat": "CAdvisor"
    },
    {
     "expr": "container_fs_usage_bytes{instance=\"131.217.179.25:8080\", name=\"traefik\"}",
     "legendFormat": "Traefik"
    }
   ]
  }
 ]
}