{
 "title": "Landing",
 "description": "[WIP] Landing summary page, for problem identification at a glance.",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admin",
   "type": "bargauge",
   "description": "System summary gauges.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1) by (instance) / count(rate(node_cpu_seconds_total{instance=\"131.217.179.250:9100\", mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "CPU"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.179.250:9100\"} - node_memory_MemAvailable_bytes{instance=\"131.217.179.250:9100\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"131.217.179.250:9100\"} - node_filesystem_avail_bytes{instance=\"131.217.179.250:9100\"})",
     "legendFormat": "Storage"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=~\"admin-grafana-1|admin-prometheus-1|admin-cadvisor-1|traefik\"})",
     "legendFormat": "Docker"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.179.250:9100\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"131.217.179.250:9100\"})",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Interactive",
   "type": "bargauge",
   "description": "System summary gauges.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1) by (instance) / count(rate(node_cpu_seconds_total{instance=\"131.217.179.90:9100\", mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "CPU"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.179.90:9100\"} - node_memory_MemAvailable_bytes{instance=\"131.217.179.90:9100\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"131.217.179.90:9100\", mountpoint=~\"/|/home|/mnt/docker\"} - node_filesystem_avail_bytes{instance=\"131.217.179.90:9100\", mountpoint=~\"/|/home|/mnt/docker\"})",
     "legendFormat": "Storage"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\"vast-jupyterhub-hub-1|vast-jupyterhub-database-1|interactive-cadvisor-1|traefik\"})",
     "legendFormat": "Docker"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.179.90:9100\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"131.217.179.90:9100\", mountpoint=~\"/|/home|/mnt/docker\"})",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "WebApp",
   "type": "bargauge",
   "description": "System summary gauges.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1) by (instance) / count(rate(node_cpu_seconds_total{instance=\"131.217.179.25:9100\", mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "CPU"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.179.25:9100\"} - node_memory_MemAvailable_bytes{instance=\"131.217.179.25:9100\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=~\"/|/mnt/docker|/mnt/postgres|/opt/vast-sys\"} - node_filesystem_avail_bytes{instance=\"131.217.179.25:9100\", mountpoint=~\"/|/mnt/docker|/mnt/postgres|/opt/vast-sys\"})",
     "legendFormat": "Storage"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\"vast-pipeline-pipeline-1|vast-pipeline-database-1|vast-pipeline-index-web-1|vast-pipeline-index-database-1|validation-app-1|validation-database-1|carta-devops-backend-1|carta-devops-database-1|radio-star-catalogue-web-1|radio-star-catalogue-db-1|pghero-app-1|webapp-cadvisor-1|traefik\"})",
     "legendFormat": "Docker"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.179.25:9100\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=~\"/|/mnt/docker|/mnt/postgres|/opt/vast-sys\"})",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Development",
   "type": "bargauge",
   "description": "System summary gauges.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1) by (instance) / count(rate(node_cpu_seconds_total{instance=\"131.217.178.98:9100\", mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "CPU"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.178.98:9100\"} - node_memory_MemAvailable_bytes{instance=\"131.217.178.98:9100\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"131.217.178.98:9100\", mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=\"131.217.178.98:9100\", mountpoint=\"/\"})",
     "legendFormat": "Storage"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.178.98:8080\", name=~\"development-cadvisor-1|traefik\"}) or vector(NaN)",
     "legendFormat": "Docker"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"131.217.178.98:9100\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"131.217.178.98:9100\", mountpoint=\"/\"})",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Storage",
   "type": "bargauge",
   "description": "System storage gauges, by mountpoint.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/mnt/docker\"} - node_filesystem_avail_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/mnt/docker\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/opt/vast-sys\"} - node_filesystem_avail_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/opt/vast-sys\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/mnt/data\"} - node_filesystem_avail_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/mnt/data\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/mnt/pipeline-runs\"} - node_filesystem_avail_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/mnt/pipeline-runs\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/mnt/docker\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/opt/vast-sys\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/mnt/data\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=\"/mnt/pipeline-runs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "bargauge",
   "description": "System storage gauges, by mountpoint.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.90:9100\", mountpoint=~\"/|/home|/mnt/docker\"} - node_filesystem_avail_bytes{instance=\"131.217.179.90:9100\", mountpoint=~\"/|/home|/opt/vast-sys|/mnt/docker\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.90:9100\", mountpoint=\"/\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.90:9100\", mountpoint=\"/mnt/docker\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.90:9100\", mountpoint=\"/home\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "bargauge",
   "description": "System storage gauges, by mountpoint.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/mnt/docker\"} - node_filesystem_avail_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/mnt/docker\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/opt/vast-sys\"} - node_filesystem_avail_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/opt/vast-sys\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/mnt/postgres\"} - node_filesystem_avail_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/mnt/postgres\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/mnt/docker\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/opt/vast-sys\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=\"/mnt/postgres\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "bargauge",
   "description": "System storage gauges, by mountpoint.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.178.98:9100\", mountpoint=~\"/\"} - node_filesystem_avail_bytes{instance=\"131.217.178.98:9100\", mountpoint=~\"/\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"131.217.178.98:9100\", mountpoint=\"/\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Docker",
   "type": "stat",
   "description": "Status of expected containers, by name.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"admin-grafana-1\"}) or on() vector(0)",
     "legendFormat": "admin-grafana-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"admin-prometheus-1\"}) or on() vector(0)",
     "legendFormat": "admin-prometheus-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"admin-cadvisor-1\"}) or on() vector(0)",
     "legendFormat": "admin-cadvisor-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=\"traefik\"}) or on() vector(0)",
     "legendFormat": "traefik"
    }
   ]
  },
  {
   "title": "Docker",
   "type": "stat",
   "description": "Status of expected containers, by name.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\"jupyter-.*\"}) or on() vector(0)",
     "legendFormat": "jupyter-[user]"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-hub-1\"}) or on() vector(0)",
     "legendFormat": "vast-jupyterhub-hub-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"vast-jupyterhub-database-1\"}) or on() vector(0)",
     "legendFormat": "vast-jupyterhub-database-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"interactive-cadvisor-1\"}) or on() vector(0)",
     "legendFormat": "interactive-cadvisor-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=\"traefik\"}) or on() vector(0)",
     "legendFormat": "traefik"
    }
   ]
  },
  {
   "title": "Docker",
   "type": "stat",
   "description": "Status of expected containers, by name.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-pipeline-1\"}) or on() vector(0)",
     "legendFormat": "vast-pipeline-pipeline-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-database-1\"}) or on() vector(0)",
     "legendFormat": "vast-pipeline-database-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-web-1\"}) or on() vector(0)",
     "legendFormat": "vast-pipeline-index-web-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"vast-pipeline-index-database-1\"}) or on() vector(0)",
     "legendFormat": "vast-pipeline-index-database-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"validation-app-1\"}) or on() vector(0)",
     "legendFormat": "validation-app-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"validation-database-1\"}) or on() vector(0)",
     "legendFormat": "validation-database-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"carta-devops-backend-1\"}) or on() vector(0)",
     "legendFormat": "carta-devops-backend-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"carta-devops-database-1\"}) or on() vector(0)",
     "legendFormat": "carta-devops-database-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-web-1\"}) or on() vector(0)",
     "legendFormat": "radio-star-catalogue-web-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"radio-star-catalogue-db-1\"}) or on() vector(0)",
     "legendFormat": "radio-star-catalogue-db-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"pghero-app-1\"}) or on() vector(0)",
     "legendFormat": "pghero-app-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"webapp-cadvisor-1\"}) or on() vector(0)",
     "legendFormat": "webapp-cadvisor-1"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=\"traefik\"}) or on() vector(0)",
     "legendFormat": "traefik"
    }
   ]
  }
 ]
}