{
 "title": "Quick View",
 "description": "At-a-glance metrics for the system as a whole.",
 "time": { "from": "2025-05-21T04:31:15.879Z", "to": "2025-05-21T16:31:15.879Z" },
 "panels": [
  { "title": "Admin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Current 1m load average.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1) by (instance) / count(rate(node_cpu_seconds_total{instance=\"131.217.179.250:9100\", mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"131.217.179.250:9100\"} - node_memory_MemAvailable_bytes{instance=\"131.217.179.250:9100\"}) / node_memory_MemTotal_bytes{instance=\"131.217.179.250:9100\"}",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "gauge",
   "description": "Current in-use disk space.",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=~\"/|/mnt.*|/opt/vast-sys\"} - node_filesystem_avail_bytes{instance=\"131.217.179.250:9100\", mountpoint=~\"/|/mnt.*|/opt/vast-sys\"}) / node_filesystem_size_bytes{instance=\"131.217.179.250:9100\", mountpoint=~\"/|/mnt.*|/opt/vast-sys\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Docker",
   "type": "stat",
   "description": "Container status.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=~\".*grafana.*|.*prometheus.*|.*cadvisor.*\"}) / 3 or on() vector(0)",
     "legendFormat": "Monitoring"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.250:8080\", name=~\".*traefik.*\"}) / 1 or on() vector(0)",
     "legendFormat": "Traefik"
    }
   ]
  },
  { "title": "Interactive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Current 1m load average.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1) by (instance) / count(rate(node_cpu_seconds_total{instance=\"131.217.179.90:9100\", mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"131.217.179.90:9100\"} - node_memory_MemAvailable_bytes{instance=\"131.217.179.90:9100\"}) / node_memory_MemTotal_bytes{instance=\"131.217.179.90:9100\"}",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "gauge",
   "description": "Current in-use disk space.",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"131.217.179.90:9100\", mountpoint=~\"/|/home|/mnt/docker\"} - node_filesystem_avail_bytes{instance=\"131.217.179.90:9100\", mountpoint=~\"/|/home|/mnt/docker\"}) / node_filesystem_size_bytes{instance=\"131.217.179.90:9100\", mountpoint=~\"/|/home|/mnt/docker\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Docker",
   "type": "stat",
   "description": "Container status.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\"jupyter-.*\"}) or on() vector(0)",
     "legendFormat": "Instances"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\".*jupyterhub-(hub|database).*\"}) / 2 or on() vector(0)",
     "legendFormat": "JupyterHub"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\".*cadvisor.*\"}) or on() vector(0)",
     "legendFormat": "Monitoring"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.90:8080\", name=~\".*traefik.*\"}) or on() vector(0)",
     "legendFormat": "Traefik"
    }
   ]
  },
  { "title": "Webapp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Current 1m load average.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1) by (instance) / count(rate(node_cpu_seconds_total{instance=\"131.217.179.25:9100\", mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"131.217.179.25:9100\"} - node_memory_MemAvailable_bytes{instance=\"131.217.179.25:9100\"}) / node_memory_MemTotal_bytes{instance=\"131.217.179.25:9100\"}",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "gauge",
   "description": "Current in-use disk space.",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=~\"/|/opt/vast-sys|/mnt/docker|/mnt/postgres\"} - node_filesystem_avail_bytes{instance=\"131.217.179.25:9100\", mountpoint=~\"/|/opt/vast-sys|/mnt/docker|/mnt/postgres\"}) / node_filesystem_size_bytes{instance=\"131.217.179.25:9100\", mountpoint=~\"/|/opt/vast-sys|/mnt/docker|/mnt/postgres\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Docker",
   "type": "stat",
   "description": "Container status.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\".*pipeline.*\"}) / 2 or on() vector(0)",
     "legendFormat": "Pipeline"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\".*validation.*\"}) / 2 or on() vector(0)",
     "legendFormat": "Validation"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\".*carta.*\"}) / 2 or on() vector(0)",
     "legendFormat": "Carta"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\".*cadvisor.*\"}) or on() vector(0)",
     "legendFormat": "Monitoring"
    },
    {
     "expr": "count(container_last_seen{instance=\"131.217.179.25:8080\", name=~\".*traefik.*\"}) or on() vector(0)",
     "legendFormat": "Traefik"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  { "title": "Development", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Current 1m load average.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1) by (instance) / count(rate(node_cpu_seconds_total{instance=\"131.217.178.98:9100\", mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"131.217.178.98:9100\"} - node_memory_MemAvailable_bytes{instance=\"131.217.178.98:9100\"}) / node_memory_MemTotal_bytes{instance=\"131.217.178.98:9100\"}",
     "legendFormat": "RAM Used"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "gauge",
   "description": "Current in-use disk space.",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"131.217.178.98:9100\", mountpoint=~\"/\"} - node_filesystem_avail_bytes{instance=\"131.217.178.98:9100\", mountpoint=~\"/\"}) / node_filesystem_size_bytes{instance=\"131.217.178.98:9100\", mountpoint=~\"/\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}