{
 "title": "System",
 "description": "Per-system performance metrics, including CPU, memory, storage, I/O, and network.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "Admin : 131.217.179.250, Interactive : 131.217.179.90, WebApp : 131.217.179.25, Development : 131.217.178.98"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Current 1m load average.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1) by (instance) / count(rate(node_cpu_seconds_total{instance=\"131.217.179.250:9100\", mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "CPU Usage History",
   "type": "timeseries",
   "description": "History of 1m load average.",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_load1) by (instance) / count(rate(node_cpu_seconds_total{instance=\"131.217.179.250:9100\", mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "description": "Current CPU usage, per core.",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_by_label(sum(rate(node_cpu_seconds_total{instance=\"$server:9100\", mode!~\"idle\", cpu=~\"0|1|2|3|4|5|6|7|8|9\"}[1m])) by (cpu),\"cpu\")",
     "legendFormat": "{{cpu}}"
    },
    {
     "expr": "sort_by_label(sum(rate(node_cpu_seconds_total{instance=\"$server:9100\", mode!~\"idle\", cpu=~\"10|11|12|13|14|15\"}[1m])) by (cpu),\"cpu\")",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Core Usage History",
   "type": "timeseries",
   "description": "History of CPU usage, per core.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$server:9100\", mode!~\"idle\"}[1m])) by (cpu)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$server:9100\"} - node_memory_MemAvailable_bytes{instance=\"$server:9100\"}) / node_memory_MemTotal_bytes{instance=\"$server:9100\"} ",
     "legendFormat": "Used RAM"
    }
   ]
  },
  {
   "title": "RAM Usage History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$server:9100\"} - node_memory_MemAvailable_bytes{instance=\"$server:9100\"}) / node_memory_MemTotal_bytes{instance=\"$server:9100\"} ",
     "legendFormat": "Used RAM"
    }
   ]
  },
  {
   "title": "Types",
   "type": "stat",
   "description": "Current in-use RAM, by type.",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"$server:9100\"} / node_memory_MemTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Mapped_bytes{instance=\"$server:9100\"} / node_memory_MemTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$server:9100\"} / node_memory_MemTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$server:9100\"} - node_memory_SwapFree_bytes{instance=\"$server:9100\"}) / node_memory_SwapTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "RAM Type History",
   "type": "timeseries",
   "description": "History of in-use RAM, by type.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"$server:9100\"} / node_memory_MemTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$server:9100\"} / node_memory_MemTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Mapped_bytes{instance=\"$server:9100\"} / node_memory_MemTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$server:9100\"} / node_memory_MemTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$server:9100\"} - node_memory_SwapFree_bytes{instance=\"$server:9100\"}) / node_memory_SwapTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Swap"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Storage Usage",
   "type": "stat",
   "description": "Current in-use disk space.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"$server:9100\"}) - sum(node_filesystem_avail_bytes{instance=\"$server:9100\"})) / sum(node_filesystem_size_bytes{instance=\"$server:9100\"})",
     "legendFormat": "Used Storage"
    }
   ]
  },
  {
   "title": "Storage Usage History",
   "type": "timeseries",
   "description": "History of in-use disk space.",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"$server:9100\"}) - sum(node_filesystem_avail_bytes{instance=\"$server:9100\"})) / sum(node_filesystem_size_bytes{instance=\"$server:9100\"})",
     "legendFormat": "Used Storage"
    }
   ]
  },
  {
   "title": "Mounts",
   "type": "stat",
   "description": "Current in-use disk space, by mount point.",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/mnt/data\"} - node_filesystem_avail_bytes{instance=\"$server:9100\"}) / node_filesystem_size_bytes{instance=\"$server:9100\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/mnt/pipeline-runs\"} - node_filesystem_avail_bytes{instance=\"$server:9100\"}) / node_filesystem_size_bytes{instance=\"$server:9100\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/home\"} - node_filesystem_avail_bytes{instance=\"$server:9100\"}) / node_filesystem_size_bytes{instance=\"$server:9100\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/mnt/docker\"} - node_filesystem_avail_bytes{instance=\"$server:9100\"}) / node_filesystem_size_bytes{instance=\"$server:9100\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Mount Usage History",
   "type": "timeseries",
   "description": "History of in-use disk space, by mount point.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/mnt/data\"} - node_filesystem_avail_bytes{instance=\"$server:9100\"}) / node_filesystem_size_bytes{instance=\"$server:9100\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/mnt/pipeline-runs\"} - node_filesystem_avail_bytes{instance=\"$server:9100\"}) / node_filesystem_size_bytes{instance=\"$server:9100\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/home\"} - node_filesystem_avail_bytes{instance=\"$server:9100\"}) / node_filesystem_size_bytes{instance=\"$server:9100\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/mnt/docker\"} - node_filesystem_avail_bytes{instance=\"$server:9100\"}) / node_filesystem_size_bytes{instance=\"$server:9100\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/\"} - node_filesystem_avail_bytes{instance=\"$server:9100\"}) / node_filesystem_size_bytes{instance=\"$server:9100\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/opt/vast-sys\"} - node_filesystem_avail_bytes{instance=\"$server:9100\"}) / node_filesystem_size_bytes{instance=\"$server:9100\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "I/O Operations",
   "type": "stat",
   "description": "Total current I/O operation rates, over given range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "I/O Operations History",
   "type": "timeseries",
   "description": "History of total I/O operations rates, over given range.",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "description": "Size of data written, over given range, per device.",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(node_disk_written_bytes_total{instance=\"$server:9100\"}[$__range])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Write History",
   "type": "timeseries",
   "description": "History of size of data written, over given range, per device.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(node_disk_written_bytes_total{instance=\"$server:9100\"}[$__range])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Network Operations",
   "type": "stat",
   "description": "Total current network operation rates, over given range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Network Operations History",
   "type": "timeseries",
   "description": "History of total network operations rates, over given range.",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "stat",
   "description": "Total size of data received / sent, over given range.",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Network Totals History",
   "type": "timeseries",
   "description": "History of total size of data received / sent, over given range.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Up"
    }
   ]
  }
 ]
}