{
 "title": "System",
 "description": "Per-system performance metrics, including CPU, memory, storage, I/O, and network.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "Admin : 131.217.179.250, Interactive : 131.217.179.90, WebApp : 131.217.179.25, Development : 131.217.178.98"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Usage",
   "type": "stat",
   "description": "Current CPU usage, by 1m, 5m, and 15m load averages.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$server:9100\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$server:9100\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"$server:9100\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Usage History",
   "type": "timeseries",
   "description": "History CPU usage, by 1m, 5m, and 15m load averages.",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$server:9100\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$server:9100\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"$server:9100\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Core Usage",
   "type": "stat",
   "description": "Current CPU usage, per core.",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(node_cpu_seconds_total{instance=\"$server:9100\", mode=\"system\"}[1m]))",
     "legendFormat": "Cores"
    },
    {
     "expr": "avg(sum(rate(node_cpu_seconds_total{instance=\"$server:9100\", mode!~\"idle\"}[1m])) by (cpu))",
     "legendFormat": "Average Load"
    }
   ]
  },
  {
   "title": "Core Usage History",
   "type": "timeseries",
   "description": "History of CPU usage, per core, as a stacked time series.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$server:9100\", mode!~\"idle\"}[1m])) by (cpu)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Usage",
   "type": "stat",
   "description": "Current in-use RAM.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$server:9100\"} - node_memory_MemAvailable_bytes{instance=\"$server:9100\"}) / node_memory_MemTotal_bytes{instance=\"$server:9100\"} ",
     "legendFormat": "Relative"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server:9100\"} - node_memory_MemAvailable_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Usage History",
   "type": "timeseries",
   "description": "History of in-use RAM.",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server:9100\"} - node_memory_MemAvailable_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Used RAM"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Used RAM"
    }
   ]
  },
  {
   "title": "Type Usage",
   "type": "bargauge",
   "description": "Current in-use RAM, by type.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$server:9100\"} - node_memory_SwapFree_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server:9100\"} - node_memory_MemAvailable_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server:9100\"} - node_memory_MemFree_bytes{instance=\"$server:9100\"}",
     "legendFormat": "Not Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$server:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Available",
   "type": "stat",
   "description": "Current available disk space.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_avail_bytes{instance=\"$server:9100\"})) / sum(node_filesystem_size_bytes{instance=\"$server:9100\"})",
     "legendFormat": "Relative"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=\"$server:9100\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"$server:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available History",
   "type": "timeseries",
   "description": "History of available disk space.",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{instance=\"$server:9100\", mountpoint=~\"/|/mnt.*|/opt.*|/home\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=~\"/|/mnt.*|/opt.*|/home\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Available Mount Space",
   "type": "bargauge",
   "description": "Current available disk space, by mount point.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"$server:9100\", mountpoint!~\"/run.*\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/opt/vast-sys\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/mnt/docker\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/home\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/mnt/postgres\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/mnt/data\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"$server:9100\", mountpoint=\"/mnt/pipeline-runs\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "I/O",
   "type": "stat",
   "description": "Total current I/O operation rates, over given range.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "I/O History",
   "type": "timeseries",
   "description": "History of I/O operation rates, over given range.",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "description": "Total current network operation rates, over given range.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Network History",
   "type": "timeseries",
   "description": "History of network operation rates, over given range.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Down"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "I/O Data",
   "type": "stat",
   "description": "Total I/O operation data, over given range.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_disk_read_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(increase(node_disk_written_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Written"
    }
   ]
  },
  {
   "title": "Network Data",
   "type": "stat",
   "description": "Total size of data received / sent, over given range.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$server:9100\"}[$__range]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}